baseURL = "http://example.org/"
languageCode = "en-us"
title = "Samy Mawon"
theme = "hugo-lithium-theme"
description = "Purr-fect Solutions"
metadataformat = "yaml"
canonifyurls = true
disqusShortname = "<your_name>"
# enableGitInfo = "true" # you can change this after git init
pygmentsUseClasses = "true"
pygmentsCodeFences = "true"


[author]
  name = "ajonp"
  homepage = "https://ajonp.com"


[taxonomies]
  authors = "authors"
  tag = "tags"
  category = "categories"
  languages = "languages"
  
[params]
  toc = "true"
  RSSLink = "/index.xml"
  author = "ajonp" 
  github = "ajonpllc" 
  twitter = "ajonpcom" 
  youtube = "<your_name>" #channelname
  email = "developer@ajonp.com"
  images = ["https://res.cloudinary.com/ajonp/image/upload/w_500/v1543267002/ajonp-ajonp-com/youtube_banner.png"]
  fb_app_id = "<your_name>"

  # Search Only
  [params.algolia]
    appId = "<your_name>"
    apiKey = "your_name"
    indexName = "your_name"
  [params.home]
    image = "https://res.cloudinary.com/ajonp/image/upload/v1544021089/ajonp-ajonp-com/Logos/ajonp/welcom_card.png"
    title = "Welcome to AJonP"
    subtitle = "Here you will find lessons and videos to coach you on your programming journey."
    showGithub = true
    showTwitter = true
    showYoutube = true

[[menu.main]]
    name = "Home"
    pre = "home"
    weight = -1
    url = "/"
[[menu.main]]
    name = "Lessons"
    pre = "school"
    weight = 100
    url = "/lessons/"
[[menu.main]]
    name = "Blog"
    pre = "book"
    weight = 200
    url = "/blog/"
[[menu.main]]
    name = "Categories"
    pre = "apps"
    weight = 300
    url = "/categories/"
[[menu.main]]
    name = "Tags"
    pre = "pricetag"
    weight = 400
    url = "/tags/"
[[menu.main]]
    name = "Coding Languages"
    pre = "code"
    weight = 500
    url = "/languages/"
[[menu.main]]
    name = "Welcome"
    pre = "welcome"
    weight = 50
    url = "http://localhost:1313/posts/"




BackUP Config Freelancer :

# Site settings
baseurl = "https://samyxid.github.io/"
languageCode = "en-us"
title = "Samy Mawon"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Mr. Samy"
    description = "My awesome description"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "samysamysamy@email.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Samy Mawon"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Samy Mawon"
        subtitle = "Newbs Gamer - Programmer - Gopher"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Potopolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "Newbs is Always Newbs."
        right = "All About Newbs !"

        [params.about.button]
            text = "Download theme"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Samy Mawon."

        [params.contact.form.email]
            text = "Email Address"
            error = "samsamsam@gmail.com"

        [params.contact.form.phone]
            text = "Phone Number"
            error = "+168 658432"

        [params.contact.form.message]
            text = "Message"
            error = "Sawadikap Skidipapap."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["3481 Melrose Place", "Beverly Hills, CA 90210"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/spf13/hugo"

            [[params.footer.social.networks]]
                icon = "fa-stack-overflow"
                link=  "//stackoverflow.com/questions/tagged/hugo"


        [params.footer.credits]
            title = "About Freelancer"
            text = "shdgfayfyuwbefhusyfuyewbfgauyfdwhbfywegfybahdfawetgfsagdf"